topologies:
  build: &build
    name: build
    cpu: 2
    memory: 3800
  master_1repl: &master_1repl
    name: master_1repl
    cpu: 4
    memory: 6450
  master_1repl_1client: &master_1repl_1client
    name: master_1repl_1client
    cpu: 4
    memory: 7400

jobs:
  fedora-29/build:
    requires: []
    priority: 100
    job:
      class: Build
      args:
        git_repo: '{git_repo}'
        git_refspec: '{git_refspec}'
        template: &ci-master-f29
          name: freeipa/ci-master-f29
          version: 0.2.0
        timeout: 1800
        topology: *build

  fedora-29/test_ntp_options:
    requires: [fedora-29/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{fedora-29/build_url}'
        test_suite: test_integration/test_ntp_options.py::TestNTPoptions
        template: *ci-master-f29
        timeout: 14400
        topology: *master_1repl_1client
