topologies:
  build: &build
    name: build
    cpu: 2
    memory: 3800
  master_1repl: &master_1repl
    name: master_1repl
    cpu: 4
    memory: 6450
  master_1repl_1client: &master_1repl_1client
    name: master_1repl_1client
    cpu: 4
    memory: 7400
  ipaserver: &ipaserver
    name: ipaserver
    cpu: 2
    memory: 2400
  master_2repl_1client: &master_2repl_1client
    name: master_2repl_1client
    cpu: 5
    memory: 10150
  master_3repl_1client: &master_3repl_1client
    name: master_3repl_1client
    cpu: 6
    memory: 12900

jobs:
  389ds-fedora/build:
    requires: []
    priority: 100
    job:
      class: Build
      args:
        git_repo: '{git_repo}'
        git_refspec: '{git_refspec}'
        template: &389ds-master-latest
          name: freeipa/389ds-master-f34
          version: 0.0.1
        timeout: 1800
        topology: *build

  389ds-fedora/simple_replication:
    requires: [389ds-fedora/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{389ds-fedora/build_url}'
        update_packages: True
        test_suite: test_integration/test_simple_replication.py
        template: *389ds-master-latest
        timeout: 3600
        topology: *master_1repl

  389ds-fedora/test_commands:
    requires: [389ds-fedora/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{389ds-fedora/build_url}'
        update_packages: True
        test_suite: test_integration/test_commands.py
        template: *389ds-master-latest
        timeout: 3600
        topology: *master_1repl_1client

  389ds-fedora/test_server_del:
    requires: [389ds-fedora/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{389ds-fedora/build_url}'
        update_packages: True
        test_suite: test_integration/test_server_del.py
        template: *389ds-master-latest
        timeout: 10800
        topology: *master_2repl_1client

  389ds-fedora/test_installation_TestInstallWithCA1:
    requires: [389ds-fedora/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{389ds-fedora/build_url}'
        update_packages: True
        test_suite: test_integration/test_installation.py::TestInstallWithCA1
        template: *389ds-master-latest
        timeout: 10800
        topology: *master_3repl_1client

  389ds-fedora/test_caless_TestServerInstall:
    requires: [389ds-fedora/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{389ds-fedora/build_url}'
        update_packages: True
        test_suite: test_integration/test_caless.py::TestServerInstall
        template: *389ds-master-latest
        timeout: 12000
        topology: *master_1repl

  389ds-fedora/test_caless_TestReplicaInstall:
    requires: [389ds-fedora/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{389ds-fedora/build_url}'
        update_packages: True
        test_suite: test_integration/test_caless.py::TestReplicaInstall
        template: *389ds-master-latest
        timeout: 7200
        topology: *master_1repl

  389ds-fedora/test_caless_TestClientInstall:
    requires: [389ds-fedora/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{389ds-fedora/build_url}'
        update_packages: True
        test_suite: test_integration/test_caless.py::TestClientInstall
        template: *389ds-master-latest
        timeout: 5400
        # actually master_1client
        topology: *master_1repl_1client

  389ds-fedora/test_caless_TestCertInstall:
    requires: [389ds-fedora/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{389ds-fedora/build_url}'
        update_packages: True
        test_suite: test_integration/test_caless.py::TestCertInstall
        template: *389ds-master-latest
        timeout: 5400
        topology: *master_1repl

  389ds-fedora/test_backup_and_restore_TestUserRootFilesOwnershipPermission:
    requires: [389ds-fedora/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{389ds-fedora/build_url}'
        update_packages: True
        test_suite: test_integration/test_backup_and_restore.py::TestUserRootFilesOwnershipPermission
        template: *389ds-master-latest
        timeout: 7200
        topology: *master_1repl

  389ds-fedora/test_backup_and_restore_TestBackupAndRestore:
    requires: [389ds-fedora/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{389ds-fedora/build_url}'
        update_packages: True
        test_suite: test_integration/test_backup_and_restore.py::TestBackupAndRestore
        template: *389ds-master-latest
        timeout: 7200
        topology: *master_1repl

  389ds-fedora/test_backup_and_restore_TestBackupAndRestoreWithDNSSEC:
    requires: [389ds-fedora/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{389ds-fedora/build_url}'
        update_packages: True
        test_suite: test_integration/test_backup_and_restore.py::TestBackupAndRestoreWithDNSSEC
        template: *389ds-master-latest
        timeout: 7200
        topology: *master_1repl

  389ds-fedora/test_backup_and_restore_TestBackupReinstallRestoreWithDNSSEC:
    requires: [389ds-fedora/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{389ds-fedora/build_url}'
        update_packages: True
        test_suite: test_integration/test_backup_and_restore.py::TestBackupReinstallRestoreWithDNSSEC
        template: *389ds-master-latest
        timeout: 7200
        topology: *master_1repl

  389ds-fedora/test_backup_and_restore_TestBackupAndRestoreWithDNS:
    requires: [389ds-fedora/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{389ds-fedora/build_url}'
        update_packages: True
        test_suite: test_integration/test_backup_and_restore.py::TestBackupAndRestoreWithDNS
        template: *389ds-master-latest
        timeout: 7200
        topology: *master_1repl

  389ds-fedora/test_backup_and_restore_TestBackupReinstallRestoreWithDNS:
    requires: [389ds-fedora/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{389ds-fedora/build_url}'
        update_packages: True
        test_suite: test_integration/test_backup_and_restore.py::TestBackupReinstallRestoreWithDNS
        template: *389ds-master-latest
        timeout: 7200
        topology: *master_1repl

  389ds-fedora/test_backup_and_restore_TestBackupAndRestoreWithKRA:
    requires: [389ds-fedora/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{389ds-fedora/build_url}'
        update_packages: True
        test_suite: test_integration/test_backup_and_restore.py::TestBackupAndRestoreWithKRA
        template: *389ds-master-latest
        timeout: 7200
        topology: *master_1repl

  389ds-fedora/test_backup_and_restore_TestBackupReinstallRestoreWithKRA:
    requires: [389ds-fedora/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{389ds-fedora/build_url}'
        update_packages: True
        test_suite: test_integration/test_backup_and_restore.py::TestBackupReinstallRestoreWithKRA
        template: *389ds-master-latest
        timeout: 7200
        topology: *master_1repl

  389ds-fedora/test_backup_and_restore_TestBackupAndRestoreWithReplica:
    requires: [389ds-fedora/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{389ds-fedora/build_url}'
        update_packages: True
        test_suite: test_integration/test_backup_and_restore.py::TestBackupAndRestoreWithReplica
        template: *389ds-master-latest
        timeout: 7200
        topology: *master_2repl_1client

  389ds-fedora/test_backup_and_restore_TestBackupAndRestoreDMPassword:
    requires: [389ds-fedora/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{389ds-fedora/build_url}'
        update_packages: True
        test_suite: test_integration/test_backup_and_restore.py::TestBackupAndRestoreDMPassword
        template: *389ds-master-latest
        timeout: 7200
        topology: *master_1repl

  389ds-fedora/test_backup_and_restore_TestReplicaInstallAfterRestore:
    requires: [389ds-fedora/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{389ds-fedora/build_url}'
        update_packages: True
        test_suite: test_integration/test_backup_and_restore.py::TestReplicaInstallAfterRestore
        template: *389ds-master-latest
        timeout: 7200
        topology: *master_2repl_1client

  389ds-fedora/test_dnssec:
    requires: [389ds-fedora/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{389ds-fedora/build_url}'
        update_packages: True
        test_suite: test_integration/test_dnssec.py
        template: *389ds-master-latest
        timeout: 10800
        topology: *master_2repl_1client

  389ds-fedora/test_replica_promotion_TestReplicaPromotionLevel1:
    requires: [389ds-fedora/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{389ds-fedora/build_url}'
        update_packages: True
        test_suite: test_integration/test_replica_promotion.py::TestReplicaPromotionLevel1
        template: *389ds-master-latest
        timeout: 7200
        topology: *master_1repl

  389ds-fedora/test_replica_promotion_TestProhibitReplicaUninstallation:
    requires: [389ds-fedora/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{389ds-fedora/build_url}'
        update_packages: True
        test_suite: test_integration/test_replica_promotion.py::TestProhibitReplicaUninstallation
        template: *389ds-master-latest
        timeout: 7200
        topology: *master_2repl_1client

  389ds-fedora/test_replica_promotion_TestHiddenReplicaPromotion:
    requires: [389ds-fedora/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{389ds-fedora/build_url}'
        update_packages: True
        test_suite: test_integration/test_replica_promotion.py::TestHiddenReplicaPromotion
        template: *389ds-master-latest
        timeout: 7200
        topology: *master_2repl_1client

  389ds-fedora/test_upgrade:
    requires: [389ds-fedora/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{389ds-fedora/build_url}'
        update_packages: True
        test_suite: test_integration/test_upgrade.py
        template: *389ds-master-latest
        timeout: 7200
        topology: *master_1repl

  389ds-fedora/test_topology_TestCASpecificRUVs:
    requires: [389ds-fedora/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{389ds-fedora/build_url}'
        update_packages: True
        test_suite: test_integration/test_topology.py::TestCASpecificRUVs
        template: *389ds-master-latest
        timeout: 7200
        topology: *master_3repl_1client

  389ds-fedora/test_topology_TestTopologyOptions:
    requires: [389ds-fedora/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{389ds-fedora/build_url}'
        update_packages: True
        test_suite: test_integration/test_topology.py::TestTopologyOptions
        template: *389ds-master-latest
        timeout: 7200
        topology: *master_3repl_1client

  389ds-fedora/test_replication_layouts_TestLineTopologyWithoutCA:
    requires: [389ds-fedora/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{389ds-fedora/build_url}'
        update_packages: True
        test_suite: test_integration/test_replication_layouts.py::TestLineTopologyWithoutCA
        template: *389ds-master-latest
        timeout: 7200
        topology: *master_3repl_1client

  389ds-fedora/test_replication_layouts_TestLineTopologyWithCA:
    requires: [389ds-fedora/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{389ds-fedora/build_url}'
        update_packages: True
        test_suite: test_integration/test_replication_layouts.py::TestLineTopologyWithCA
        template: *389ds-master-latest
        timeout: 10800
        topology: *master_3repl_1client

  389ds-fedora/test_replication_layouts_TestLineTopologyWithCAKRA:
    requires: [389ds-fedora/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{389ds-fedora/build_url}'
        update_packages: True
        test_suite: test_integration/test_replication_layouts.py::TestLineTopologyWithCAKRA
        template: *389ds-master-latest
        timeout: 10800
        topology: *master_3repl_1client

  389ds-fedora/test_replication_layouts.py_TestStarTopologyWithoutCA:
    requires: [389ds-fedora/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{389ds-fedora/build_url}'
        update_packages: True
        test_suite: test_integration/test_replication_layouts.py::TestStarTopologyWithoutCA
        template: *389ds-master-latest
        timeout: 7200
        topology: *master_3repl_1client

  389ds-fedora/test_replication_layouts_TestStarTopologyWithCA:
    requires: [389ds-fedora/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{389ds-fedora/build_url}'
        update_packages: True
        test_suite: test_integration/test_replication_layouts.py::TestStarTopologyWithCA
        template: *389ds-master-latest
        timeout: 7200
        topology: *master_3repl_1client

  389ds-fedora/test_replication_layouts_TestStarTopologyWithCAKRA:
    requires: [389ds-fedora/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{389ds-fedora/build_url}'
        update_packages: True
        test_suite: test_integration/test_replication_layouts.py::TestStarTopologyWithCAKRA
        template: *389ds-master-latest
        timeout: 10800
        topology: *master_3repl_1client

  389ds-fedora/test_replication_layouts_TestCompleteTopologyWithoutCA:
    requires: [389ds-fedora/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{389ds-fedora/build_url}'
        update_packages: True
        test_suite: test_integration/test_replication_layouts.py::TestCompleteTopologyWithoutCA
        template: *389ds-master-latest
        timeout: 7200
        topology: *master_3repl_1client

  389ds-fedora/test_replication_layouts_TestCompleteTopologyWithCA:
    requires: [389ds-fedora/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{389ds-fedora/build_url}'
        update_packages: True
        test_suite: test_integration/test_replication_layouts.py::TestCompleteTopologyWithCA
        template: *389ds-master-latest
        timeout: 7200
        topology: *master_3repl_1client

  389ds-fedora/test_replication_layouts_TestCompleteTopologyWithCAKRA:
    requires: [389ds-fedora/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{389ds-fedora/build_url}'
        update_packages: True
        test_suite: test_integration/test_replication_layouts.py::TestCompleteTopologyWithCAKRA
        template: *389ds-master-latest
        timeout: 7200
        topology: *master_3repl_1client

  389ds-fedora/test_client_uninstallation:
    requires: [389ds-fedora/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{389ds-fedora/build_url}'
        update_packages: True
        test_suite: test_integration/test_uninstallation.py
        template: *389ds-master-latest
        timeout: 7200
        topology: *master_1repl_1client

  389ds-fedora/customized_ds_config_install:
    requires: [389ds-fedora/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{389ds-fedora/build_url}'
        update_packages: True
        test_suite: test_integration/test_customized_ds_config_install.py
        template: *389ds-master-latest
        timeout: 3600
        topology: *master_1repl

  389ds-fedora/dns_locations:
    requires: [389ds-fedora/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{389ds-fedora/build_url}'
        update_packages: True
        test_suite: test_integration/test_dns_locations.py
        template: *389ds-master-latest
        timeout: 3600
        topology: *master_2repl_1client

  389ds-fedora/external_ca_TestExternalCAdirsrvStop:
    requires: [389ds-fedora/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{389ds-fedora/build_url}'
        update_packages: True
        test_suite: test_integration/test_external_ca.py::TestExternalCAdirsrvStop
        template: *389ds-master-latest
        timeout: 3600
        topology: *master_1repl

  389ds-fedora/mask:
    requires: [389ds-fedora/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{389ds-fedora/build_url}'
        update_packages: True
        test_suite: test_integration/test_installation.py::TestMaskInstall
        template: *389ds-master-latest
        timeout: 3600
        topology: *master_1repl

  389ds-fedora/automember:
    requires: [389ds-fedora/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{389ds-fedora/build_url}'
        update_packages: True
        test_suite: test_integration/test_automember.py
        template: *389ds-master-latest
        timeout: 3600
        topology: *master_1repl

  389ds-fedora/test_fips:
    requires: [389ds-fedora/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{389ds-fedora/build_url}'
        update_packages: True
        test_suite: test_integration/test_fips.py
        template: *389ds-master-latest
        timeout: 7200
        topology: *master_1repl_1client

  389ds-fedora/test_pwpolicy:
    requires: [389ds-fedora/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{389ds-fedora/build_url}'
        update_packages: True
        test_suite: test_integration/test_pwpolicy.py
        template: *389ds-master-latest
        timeout: 3600
        topology: *master_1repl
