topologies:
  build: &build
    name: build
    cpu: 2
    memory: 3800
  master_3client: &master_3client
    name: master_3client
    cpu: 5
    memory: 10150
  master_1repl: &master_1repl
    name: master_1repl
    cpu: 4
    memory: 6450
  master_1repl_1client: &master_1repl_1client
    name: master_1repl_1client
    cpu: 4
    memory: 7400
  ipaserver: &ipaserver
    name: ipaserver
    cpu: 2
    memory: 2400
  master_2repl_1client: &master_2repl_1client
    name: master_2repl_1client
    cpu: 5
    memory: 10150
  master_3repl_1client: &master_3repl_1client
    name: master_3repl_1client
    cpu: 6
    memory: 12900
  ad_master_2client: &ad_master_2client
    name: ad_master_2client
    cpu: 4
    memory: 12000
  ad_master: &ad_master
    name: ad_master
    cpu: 4
    memory: 12000
  adroot_adchild_adtree_master_1client: &adroot_adchild_adtree_master_1client
    name: adroot_adchild_adtree_master_1client
    cpu: 8
    memory: 14500

jobs:
  fedora-latest/build:
    requires: []
    priority: 100
    job:
      class: Build
      args:
        git_repo: '{git_repo}'
        git_refspec: '{git_refspec}'
        template: &ci-master-latest
          name: freeipa/bind-master-f35
          version: 0.0.2
        timeout: 1800
        topology: *build


  fedora-latest/test_installation_TestInstallWithCA_DNS1:
    requires: [fedora-latest/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{fedora-latest/build_url}'
        test_suite: test_integration/test_installation.py::TestInstallWithCA_DNS1
        template: *ci-master-latest
        timeout: 10800
        topology: *master_3repl_1client

  fedora-latest/test_installation_TestInstallWithCA_DNS2:
    requires: [fedora-latest/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{fedora-latest/build_url}'
        test_suite: test_integration/test_installation.py::TestInstallWithCA_DNS2
        template: *ci-master-latest
        timeout: 10800
        topology: *master_3repl_1client

  fedora-latest/test_installation_TestInstallWithCA_DNS3:
    requires: [fedora-latest/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{fedora-latest/build_url}'
        test_suite: test_integration/test_installation.py::TestInstallWithCA_DNS3
        template: *ci-master-latest
        timeout: 3600
        topology: *master_1repl

  fedora-latest/test_installation_TestInstallWithCA_DNS4:
    requires: [fedora-latest/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{fedora-latest/build_url}'
        test_suite: test_integration/test_installation.py::TestInstallWithCA_DNS4
        template: *ci-master-latest
        timeout: 3600
        topology: *master_1repl

  fedora-latest/test_installation_TestInstallWithCA_KRA_DNS1:
    requires: [fedora-latest/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{fedora-latest/build_url}'
        test_suite: test_integration/test_installation.py::TestInstallWithCA_KRA_DNS1
        template: *ci-master-latest
        timeout: 10800
        topology: *master_3repl_1client

  fedora-latest/test_installation_TestInstallWithCA_KRA_DNS2:
    requires: [fedora-latest/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{fedora-latest/build_url}'
        test_suite: test_integration/test_installation.py::TestInstallWithCA_KRA_DNS2
        template: *ci-master-latest
        timeout: 10800
        topology: *master_3repl_1client

  fedora-latest/test_installation_TestInstallMaster:
    requires: [fedora-latest/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{fedora-latest/build_url}'
        test_suite: test_integration/test_installation.py::TestInstallMaster
        template: *ci-master-latest
        timeout: 10800
        topology: *master_1repl


  fedora-latest/test_installation_TestInstallMasterDNS:
    requires: [fedora-latest/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{fedora-latest/build_url}'
        test_suite: test_integration/test_installation.py::TestInstallMasterDNS
        template: *ci-master-latest
        timeout: 10800
        topology: *master_1repl

  fedora-latest/test_installation_TestInstallMasterDNSRepeatedly:
    requires: [fedora-latest/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{fedora-latest/build_url}'
        test_suite: test_integration/test_installation.py::TestInstallMasterDNSRepeatedly
        template: *ci-master-latest
        timeout: 10800
        topology: *master_1repl

  fedora-latest/test_installation_TestInstallMasterReservedIPasForwarder:
    requires: [fedora-latest/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{fedora-latest/build_url}'
        test_suite: test_integration/test_installation.py::TestInstallMasterReservedIPasForwarder
        template: *ci-master-latest
        timeout: 10800
        topology: *master_1repl

  fedora-latest/test_installation_TestInstallMasterReplica:
    requires: [fedora-latest/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{fedora-latest/build_url}'
        test_suite: test_integration/test_installation.py::TestInstallMasterReplica
        template: *ci-master-latest
        timeout: 10800
        topology: *master_1repl

  fedora-latest/test_installation_TestInstallReplicaAgainstSpecificServer:
    requires: [fedora-latest/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{fedora-latest/build_url}'
        test_suite: test_integration/test_installation.py::TestInstallReplicaAgainstSpecificServer
        template: *ci-master-latest
        timeout: 10800
        topology: *master_2repl_1client

  fedora-latest/test_installation_TestADTrustInstall:
    requires: [fedora-latest/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{fedora-latest/build_url}'
        test_suite: test_integration/test_installation.py::TestADTrustInstall
        template: *ci-master-latest
        timeout: 10800
        topology: *master_2repl_1client

  fedora-latest/test_installation_TestADTrustInstallWithDNS_KRA_ADTrust:
    requires: [fedora-latest/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{fedora-latest/build_url}'
        test_suite: test_integration/test_installation.py::TestADTrustInstallWithDNS_KRA_ADTrust
        template: *ci-master-latest
        timeout: 10800
        topology: *master_2repl_1client


  fedora-latest/test_caless_TestServerInstall:
    requires: [fedora-latest/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{fedora-latest/build_url}'
        test_suite: test_integration/test_caless.py::TestServerInstall
        template: *ci-master-latest
        timeout: 12000
        topology: *master_1repl

  fedora-latest/test_caless_TestReplicaInstall:
    requires: [fedora-latest/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{fedora-latest/build_url}'
        test_suite: test_integration/test_caless.py::TestReplicaInstall
        template: *ci-master-latest
        timeout: 7200
        topology: *master_1repl

  fedora-latest/test_caless_TestClientInstall:
    requires: [fedora-latest/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{fedora-latest/build_url}'
        test_suite: test_integration/test_caless.py::TestClientInstall
        template: *ci-master-latest
        timeout: 5400
        # actually master_1client
        topology: *master_1repl_1client


  fedora-latest/test_backup_and_restore_TestBackupAndRestoreWithDNSSEC:
    requires: [fedora-latest/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{fedora-latest/build_url}'
        test_suite: test_integration/test_backup_and_restore.py::TestBackupAndRestoreWithDNSSEC
        template: *ci-master-latest
        timeout: 7200
        topology: *master_1repl

  fedora-latest/test_backup_and_restore_TestBackupReinstallRestoreWithDNSSEC:
    requires: [fedora-latest/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{fedora-latest/build_url}'
        test_suite: test_integration/test_backup_and_restore.py::TestBackupReinstallRestoreWithDNSSEC
        template: *ci-master-latest
        timeout: 7200
        topology: *master_1repl

  fedora-latest/test_backup_and_restore_TestBackupAndRestoreWithDNS:
    requires: [fedora-latest/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{fedora-latest/build_url}'
        test_suite: test_integration/test_backup_and_restore.py::TestBackupAndRestoreWithDNS
        template: *ci-master-latest
        timeout: 7200
        topology: *master_1repl

  fedora-latest/test_backup_and_restore_TestBackupReinstallRestoreWithDNS:
    requires: [fedora-latest/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{fedora-latest/build_url}'
        test_suite: test_integration/test_backup_and_restore.py::TestBackupReinstallRestoreWithDNS
        template: *ci-master-latest
        timeout: 7200
        topology: *master_1repl


  fedora-latest/test_dnssec:
    requires: [fedora-latest/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{fedora-latest/build_url}'
        test_suite: test_integration/test_dnssec.py
        template: *ci-master-latest
        timeout: 10800
        topology: *master_2repl_1client


  fedora-latest/test_upgrade:
    requires: [fedora-latest/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{fedora-latest/build_url}'
        test_suite: test_integration/test_upgrade.py
        template: *ci-master-latest
        timeout: 7200
        topology: *master_1repl


  fedora-latest/test_installation_client:
    requires: [fedora-latest/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{fedora-latest/build_url}'
        test_suite: test_integration/test_installation_client.py
        template: *ci-master-latest
        timeout: 3600
        topology: *master_3client



  fedora-latest/customized_ds_config_install:
    requires: [fedora-latest/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{fedora-latest/build_url}'
        test_suite: test_integration/test_customized_ds_config_install.py
        template: *ci-master-latest
        timeout: 3600
        topology: *master_1repl

  fedora-latest/dns_locations:
    requires: [fedora-latest/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{fedora-latest/build_url}'
        test_suite: test_integration/test_dns_locations.py
        template: *ci-master-latest
        timeout: 3600
        topology: *master_2repl_1client


  fedora-latest/test_ipahealthcheck_nodns_extca_file:
    requires: [fedora-latest/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{fedora-latest/build_url}'
        test_suite: test_integration/test_ipahealthcheck.py::TestIpaHealthCheckWithoutDNS test_integration/test_ipahealthcheck.py::TestIpaHealthCheckWithExternalCA test_integration/test_ipahealthcheck.py::TestIpaHealthCheckFileCheck
        template: *ci-master-latest
        timeout: 5400
        topology: *master_1repl




  fedora-latest/test_ca_custom_sdn:
    requires: [fedora-latest/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{fedora-latest/build_url}'
        test_suite: test_integration/test_ca_custom_sdn.py
        template: *ci-master-latest
        timeout: 7200
        topology: *master_1repl

  fedora-latest/test_dns:
    requires: [fedora-latest/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{fedora-latest/build_url}'
        test_suite: test_integration/test_dns.py
        template: *ci-master-latest
        timeout: 3600
        topology: *master_1repl


