topologies:
  build: &build
    name: build
    cpu: 2
    memory: 3800
  master_1repl: &master_1repl
    name: master_1repl
    cpu: 4
    memory: 6450
  master_1repl_1client: &master_1repl_1client
    name: master_1repl_1client
    cpu: 4
    memory: 7400
  ipaserver: &ipaserver
    name: ipaserver
    cpu: 2
    memory: 2400
  master_2repl_1client: &master_2repl_1client
    name: master_2repl_1client
    cpu: 5
    memory: 10150
  master_3repl_1client: &master_3repl_1client
    name: master_3repl_1client
    cpu: 6
    memory: 12900

jobs:
  389ds-fedora/build:
    requires: []
    priority: 100
    job:
      class: Build
      args:
        copr: 'tbordaz/F20buildDS389'
        git_repo: '{git_repo}'
        git_refspec: '{git_refspec}'
        template: &ci-master-latest
          name: freeipa/ci-master-f36
          version: 0.0.7
        timeout: 1800
        topology: *build

  389ds-fedora/simple_replication:
    requires: [389ds-fedora/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{389ds-fedora/build_url}'
        update_packages: True
        copr: 'tbordaz/F20buildDS389'
        test_suite: test_integration/test_simple_replication.py
        template: *ci-master-latest
        timeout: 3600
        topology: *master_1repl
