#
# Template for temporary test commit
#
# $ ln -sf ipatests/prci_definitions/temp_commit.yaml .freeipa-pr-ci.yaml
#

topologies:
  build: &build
    name: build
    cpu: 2
    memory: 3800
  master_1repl: &master_1repl
    name: master_1repl
    cpu: 4
    memory: 6450
  master_1repl_1client: &master_1repl_1client
    name: master_1repl_1client
    cpu: 4
    memory: 7400
  ipaserver: &ipaserver
    name: ipaserver
    cpu: 2
    memory: 2400
  master_2repl_1client: &master_2repl_1client
    name: master_2repl_1client
    cpu: 5
    memory: 10150
  master_3repl_1client: &master_3repl_1client
    name: master_3repl_1client
    cpu: 6
    memory: 12900

jobs:
  389ds-fedora/build:
    requires: []
    priority: 100
    job:
      class: Build
      args:
        git_repo: '{git_repo}'
        git_refspec: '{git_refspec}'
        template: &389ds-master-latest
          name: freeipa/389ds-master-f32
          version: 0.0.2
        timeout: 1800
        topology: *build

  389ds-fedora/test_dnssec_1:
    requires: [389ds-fedora/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{389ds-fedora/build_url}'
        update_packages: True
        test_suite: test_integration/test_dnssec.py
        template: *389ds-master-latest
        timeout: 10800
        topology: *master_2repl_1client

  389ds-fedora/test_dnssec_2:
    requires: [389ds-fedora/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{389ds-fedora/build_url}'
        update_packages: True
        test_suite: test_integration/test_dnssec.py
        template: *389ds-master-latest
        timeout: 10800
        topology: *master_2repl_1client

  389ds-fedora/test_dnssec_3:
    requires: [389ds-fedora/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{389ds-fedora/build_url}'
        update_packages: True
        test_suite: test_integration/test_dnssec.py
        template: *389ds-master-latest
        timeout: 10800
        topology: *master_2repl_1client

  389ds-fedora/test_dnssec_4:
    requires: [389ds-fedora/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{389ds-fedora/build_url}'
        update_packages: True
        test_suite: test_integration/test_dnssec.py
        template: *389ds-master-latest
        timeout: 10800
        topology: *master_2repl_1client

  389ds-fedora/test_dnssec_5:
    requires: [389ds-fedora/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{389ds-fedora/build_url}'
        update_packages: True
        test_suite: test_integration/test_dnssec.py
        template: *389ds-master-latest
        timeout: 10800
        topology: *master_2repl_1client
