#
# Template for temporary test commit
#
# $ ln -sf ipatests/prci_definitions/temp_commit.yaml .freeipa-pr-ci.yaml
#

topologies:
  build: &build
    name: build
    cpu: 2
    memory: 3800
  master_3client: &master_3client
    name: master_3client
    cpu: 5
    memory: 10150
  master_1repl: &master_1repl
    name: master_1repl
    cpu: 4
    memory: 6450
  master_1repl_1client: &master_1repl_1client
    name: master_1repl_1client
    cpu: 4
    memory: 7400
  ipaserver: &ipaserver
    name: ipaserver
    cpu: 2
    memory: 2400
  master_2repl_1client: &master_2repl_1client
    name: master_2repl_1client
    cpu: 5
    memory: 10150
  master_3repl_1client: &master_3repl_1client
    name: master_3repl_1client
    cpu: 6
    memory: 12900
  ad_master_2client: &ad_master_2client
    name: ad_master_2client
    cpu: 4
    memory: 12000
  ad_master: &ad_master
    name: ad_master
    cpu: 4
    memory: 12000
  adroot_adchild_adtree_master_1client: &adroot_adchild_adtree_master_1client
    name: adroot_adchild_adtree_master_1client
    cpu: 8
    memory: 14500

jobs:
  fedora-latest/build:
    requires: []
    priority: 100
    job:
      class: Build
      args:
        git_repo: '{git_repo}'
        git_refspec: '{git_refspec}'
        template: &ci-master-latest
          name: freeipa/ci-master-f35
          version: 0.0.5
        timeout: 1800
        topology: *build

  fedora-latest/temp_commit:
    requires: [fedora-latest/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{fedora-latest/build_url}'
        test_suite: test_integration/test_replica_promotion.py::TestSubCAkeyReplication
        template: *ci-master-latest
        timeout: 7200
        topology: *master_1repl

  pki-fedora/build:
    requires: []
    priority: 100
    job:
      class: Build
      args:
        git_repo: '{git_repo}'
        git_refspec: '{git_refspec}'
        template: &pki-master-latest
          name: freeipa/pki-master-f35
          version: 0.0.1
        timeout: 1800
        topology: *build

  pki-fedora/test_replica_promotion_TestSubCAkeyReplication:
    requires: [pki-fedora/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{pki-fedora/build_url}'
        update_packages: True
        test_suite: test_integration/test_replica_promotion.py::TestSubCAkeyReplication
        template: *pki-master-latest
        timeout: 7200
        topology: *master_1repl

