#
# Template for temporary test commit
#
# $ ln -sf ipatests/prci_definitions/temp_commit.yaml .freeipa-pr-ci.yaml
#

topologies:
  build: &build
    name: build
    cpu: 2
    memory: 3800
  master_3client: &master_3client
    name: master_3client
    cpu: 5
    memory: 10150
  master_1repl: &master_1repl
    name: master_1repl
    cpu: 4
    memory: 6450
  master_1repl_1client: &master_1repl_1client
    name: master_1repl_1client
    cpu: 4
    memory: 7400
  ipaserver: &ipaserver
    name: ipaserver
    cpu: 2
    memory: 2400
  master_2repl_1client: &master_2repl_1client
    name: master_2repl_1client
    cpu: 5
    memory: 10150
  master_3repl_1client: &master_3repl_1client
    name: master_3repl_1client
    cpu: 6
    memory: 12900
  ad_master_2client: &ad_master_2client
    name: ad_master_2client
    cpu: 4
    memory: 12000
  ad_master: &ad_master
    name: ad_master
    cpu: 4
    memory: 12000
  adroot_adchild_adtree_master_1client: &adroot_adchild_adtree_master_1client
    name: adroot_adchild_adtree_master_1client
    cpu: 8
    memory: 14500

jobs:
  fedora-latest/build:
    requires: []
    priority: 100
    job:
      class: Build
      args:
        git_repo: '{git_repo}'
        git_refspec: '{git_refspec}'
        template: &ci-master-latest
          name: freeipa/ci-master-f31
          version: 0.0.4
        timeout: 1800
        topology: *build

  fedora-latest/test_trust_1:
    requires: [fedora-latest/build]
    priority: 50
    job:
      class: RunADTests
      args:
        build_url: '{fedora-latest/build_url}'
        test_suite: test_integration/test_trust.py::TestTrust
        template: *ci-master-latest
        timeout: 7200
        topology: *adroot_adchild_adtree_master_1client

  fedora-latest/test_trust_2:
    requires: [fedora-latest/build]
    priority: 50
    job:
      class: RunADTests
      args:
        build_url: '{fedora-latest/build_url}'
        test_suite: test_integration/test_trust.py::TestTrust
        template: *ci-master-latest
        timeout: 7200
        topology: *adroot_adchild_adtree_master_1client

  fedora-latest/test_trust_3:
    requires: [fedora-latest/build]
    priority: 50
    job:
      class: RunADTests
      args:
        build_url: '{fedora-latest/build_url}'
        test_suite: test_integration/test_trust.py::TestTrust
        template: *ci-master-latest
        timeout: 7200
        topology: *adroot_adchild_adtree_master_1client

  fedora-latest/test_trust_4:
    requires: [fedora-latest/build]
    priority: 50
    job:
      class: RunADTests
      args:
        build_url: '{fedora-latest/build_url}'
        test_suite: test_integration/test_trust.py::TestTrust
        template: *ci-master-latest
        timeout: 7200
        topology: *adroot_adchild_adtree_master_1client

  fedora-latest/test_trust_5:
    requires: [fedora-latest/build]
    priority: 50
    job:
      class: RunADTests
      args:
        build_url: '{fedora-latest/build_url}'
        test_suite: test_integration/test_trust.py::TestTrust
        template: *ci-master-latest
        timeout: 7200
        topology: *adroot_adchild_adtree_master_1client

  fedora-latest/test_trust_6:
    requires: [fedora-latest/build]
    priority: 50
    job:
      class: RunADTests
      args:
        build_url: '{fedora-latest/build_url}'
        test_suite: test_integration/test_trust.py::TestTrust
        template: *ci-master-latest
        timeout: 7200
        topology: *adroot_adchild_adtree_master_1client

  fedora-latest/test_trust_7:
    requires: [fedora-latest/build]
    priority: 50
    job:
      class: RunADTests
      args:
        build_url: '{fedora-latest/build_url}'
        test_suite: test_integration/test_trust.py::TestTrust
        template: *ci-master-latest
        timeout: 7200
        topology: *adroot_adchild_adtree_master_1client

  fedora-latest/test_trust_8:
    requires: [fedora-latest/build]
    priority: 50
    job:
      class: RunADTests
      args:
        build_url: '{fedora-latest/build_url}'
        test_suite: test_integration/test_trust.py::TestTrust
        template: *ci-master-latest
        timeout: 7200
        topology: *adroot_adchild_adtree_master_1client

  fedora-latest/test_trust_9:
    requires: [fedora-latest/build]
    priority: 50
    job:
      class: RunADTests
      args:
        build_url: '{fedora-latest/build_url}'
        test_suite: test_integration/test_trust.py::TestTrust
        template: *ci-master-latest
        timeout: 7200
        topology: *adroot_adchild_adtree_master_1client

  fedora-latest/test_trust_10:
    requires: [fedora-latest/build]
    priority: 50
    job:
      class: RunADTests
      args:
        build_url: '{fedora-latest/build_url}'
        test_suite: test_integration/test_trust.py::TestTrust
        template: *ci-master-latest
        timeout: 7200
        topology: *adroot_adchild_adtree_master_1client

  fedora-latest/test_trust_11:
    requires: [fedora-latest/build]
    priority: 50
    job:
      class: RunADTests
      args:
        build_url: '{fedora-latest/build_url}'
        test_suite: test_integration/test_trust.py::TestTrust
        template: *ci-master-latest
        timeout: 7200
        topology: *adroot_adchild_adtree_master_1client

  fedora-latest/test_trust_12:
    requires: [fedora-latest/build]
    priority: 50
    job:
      class: RunADTests
      args:
        build_url: '{fedora-latest/build_url}'
        test_suite: test_integration/test_trust.py::TestTrust
        template: *ci-master-latest
        timeout: 7200
        topology: *adroot_adchild_adtree_master_1client

  fedora-latest/test_trust_13:
    requires: [fedora-latest/build]
    priority: 50
    job:
      class: RunADTests
      args:
        build_url: '{fedora-latest/build_url}'
        test_suite: test_integration/test_trust.py::TestTrust
        template: *ci-master-latest
        timeout: 7200
        topology: *adroot_adchild_adtree_master_1client

  fedora-latest/test_trust_14:
    requires: [fedora-latest/build]
    priority: 50
    job:
      class: RunADTests
      args:
        build_url: '{fedora-latest/build_url}'
        test_suite: test_integration/test_trust.py::TestTrust
        template: *ci-master-latest
        timeout: 7200
        topology: *adroot_adchild_adtree_master_1client

  fedora-latest/test_trust_15:
    requires: [fedora-latest/build]
    priority: 50
    job:
      class: RunADTests
      args:
        build_url: '{fedora-latest/build_url}'
        test_suite: test_integration/test_trust.py::TestTrust
        template: *ci-master-latest
        timeout: 7200
        topology: *adroot_adchild_adtree_master_1client

  fedora-latest/test_trust_16:
    requires: [fedora-latest/build]
    priority: 50
    job:
      class: RunADTests
      args:
        build_url: '{fedora-latest/build_url}'
        test_suite: test_integration/test_trust.py::TestTrust
        template: *ci-master-latest
        timeout: 7200
        topology: *adroot_adchild_adtree_master_1client

  fedora-latest/test_trust_17:
    requires: [fedora-latest/build]
    priority: 50
    job:
      class: RunADTests
      args:
        build_url: '{fedora-latest/build_url}'
        test_suite: test_integration/test_trust.py::TestTrust
        template: *ci-master-latest
        timeout: 7200
        topology: *adroot_adchild_adtree_master_1client

  fedora-latest/test_trust_18:
    requires: [fedora-latest/build]
    priority: 50
    job:
      class: RunADTests
      args:
        build_url: '{fedora-latest/build_url}'
        test_suite: test_integration/test_trust.py::TestTrust
        template: *ci-master-latest
        timeout: 7200
        topology: *adroot_adchild_adtree_master_1client

  fedora-latest/test_trust_19:
    requires: [fedora-latest/build]
    priority: 50
    job:
      class: RunADTests
      args:
        build_url: '{fedora-latest/build_url}'
        test_suite: test_integration/test_trust.py::TestTrust
        template: *ci-master-latest
        timeout: 7200
        topology: *adroot_adchild_adtree_master_1client

  fedora-latest/test_trust_20:
    requires: [fedora-latest/build]
    priority: 50
    job:
      class: RunADTests
      args:
        build_url: '{fedora-latest/build_url}'
        test_suite: test_integration/test_trust.py::TestTrust
        template: *ci-master-latest
        timeout: 7200
        topology: *adroot_adchild_adtree_master_1client

  fedora-latest/test_trust_21:
    requires: [fedora-latest/build]
    priority: 50
    job:
      class: RunADTests
      args:
        build_url: '{fedora-latest/build_url}'
        test_suite: test_integration/test_trust.py::TestTrust
        template: *ci-master-latest
        timeout: 7200
        topology: *adroot_adchild_adtree_master_1client

  fedora-latest/test_trust_22:
    requires: [fedora-latest/build]
    priority: 50
    job:
      class: RunADTests
      args:
        build_url: '{fedora-latest/build_url}'
        test_suite: test_integration/test_trust.py::TestTrust
        template: *ci-master-latest
        timeout: 7200
        topology: *adroot_adchild_adtree_master_1client

  fedora-latest/test_trust_23:
    requires: [fedora-latest/build]
    priority: 50
    job:
      class: RunADTests
      args:
        build_url: '{fedora-latest/build_url}'
        test_suite: test_integration/test_trust.py::TestTrust
        template: *ci-master-latest
        timeout: 7200
        topology: *adroot_adchild_adtree_master_1client

  fedora-latest/test_trust_24:
    requires: [fedora-latest/build]
    priority: 50
    job:
      class: RunADTests
      args:
        build_url: '{fedora-latest/build_url}'
        test_suite: test_integration/test_trust.py::TestTrust
        template: *ci-master-latest
        timeout: 7200
        topology: *adroot_adchild_adtree_master_1client

  fedora-latest/test_trust_25:
    requires: [fedora-latest/build]
    priority: 50
    job:
      class: RunADTests
      args:
        build_url: '{fedora-latest/build_url}'
        test_suite: test_integration/test_trust.py::TestTrust
        template: *ci-master-latest
        timeout: 7200
        topology: *adroot_adchild_adtree_master_1client

  fedora-latest/test_trust_26:
    requires: [fedora-latest/build]
    priority: 50
    job:
      class: RunADTests
      args:
        build_url: '{fedora-latest/build_url}'
        test_suite: test_integration/test_trust.py::TestTrust
        template: *ci-master-latest
        timeout: 7200
        topology: *adroot_adchild_adtree_master_1client

  fedora-latest/test_trust_27:
    requires: [fedora-latest/build]
    priority: 50
    job:
      class: RunADTests
      args:
        build_url: '{fedora-latest/build_url}'
        test_suite: test_integration/test_trust.py::TestTrust
        template: *ci-master-latest
        timeout: 7200
        topology: *adroot_adchild_adtree_master_1client

  fedora-latest/test_trust_28:
    requires: [fedora-latest/build]
    priority: 50
    job:
      class: RunADTests
      args:
        build_url: '{fedora-latest/build_url}'
        test_suite: test_integration/test_trust.py::TestTrust
        template: *ci-master-latest
        timeout: 7200
        topology: *adroot_adchild_adtree_master_1client

  fedora-latest/test_trust_29:
    requires: [fedora-latest/build]
    priority: 50
    job:
      class: RunADTests
      args:
        build_url: '{fedora-latest/build_url}'
        test_suite: test_integration/test_trust.py::TestTrust
        template: *ci-master-latest
        timeout: 7200
        topology: *adroot_adchild_adtree_master_1client

  fedora-latest/test_trust_30:
    requires: [fedora-latest/build]
    priority: 50
    job:
      class: RunADTests
      args:
        build_url: '{fedora-latest/build_url}'
        test_suite: test_integration/test_trust.py::TestTrust
        template: *ci-master-latest
        timeout: 7200
        topology: *adroot_adchild_adtree_master_1client

  fedora-latest/test_trust_31:
    requires: [fedora-latest/build]
    priority: 50
    job:
      class: RunADTests
      args:
        build_url: '{fedora-latest/build_url}'
        test_suite: test_integration/test_trust.py::TestTrust
        template: *ci-master-latest
        timeout: 7200
        topology: *adroot_adchild_adtree_master_1client

  fedora-latest/test_trust_32:
    requires: [fedora-latest/build]
    priority: 50
    job:
      class: RunADTests
      args:
        build_url: '{fedora-latest/build_url}'
        test_suite: test_integration/test_trust.py::TestTrust
        template: *ci-master-latest
        timeout: 7200
        topology: *adroot_adchild_adtree_master_1client

  fedora-latest/test_trust_33:
    requires: [fedora-latest/build]
    priority: 50
    job:
      class: RunADTests
      args:
        build_url: '{fedora-latest/build_url}'
        test_suite: test_integration/test_trust.py::TestTrust
        template: *ci-master-latest
        timeout: 7200
        topology: *adroot_adchild_adtree_master_1client

  fedora-latest/test_trust_34:
    requires: [fedora-latest/build]
    priority: 50
    job:
      class: RunADTests
      args:
        build_url: '{fedora-latest/build_url}'
        test_suite: test_integration/test_trust.py::TestTrust
        template: *ci-master-latest
        timeout: 7200
        topology: *adroot_adchild_adtree_master_1client

  fedora-latest/test_trust_35:
    requires: [fedora-latest/build]
    priority: 50
    job:
      class: RunADTests
      args:
        build_url: '{fedora-latest/build_url}'
        test_suite: test_integration/test_trust.py::TestTrust
        template: *ci-master-latest
        timeout: 7200
        topology: *adroot_adchild_adtree_master_1client

  fedora-latest/test_trust_36:
    requires: [fedora-latest/build]
    priority: 50
    job:
      class: RunADTests
      args:
        build_url: '{fedora-latest/build_url}'
        test_suite: test_integration/test_trust.py::TestTrust
        template: *ci-master-latest
        timeout: 7200
        topology: *adroot_adchild_adtree_master_1client

  fedora-latest/test_trust_37:
    requires: [fedora-latest/build]
    priority: 50
    job:
      class: RunADTests
      args:
        build_url: '{fedora-latest/build_url}'
        test_suite: test_integration/test_trust.py::TestTrust
        template: *ci-master-latest
        timeout: 7200
        topology: *adroot_adchild_adtree_master_1client

  fedora-latest/test_trust_38:
    requires: [fedora-latest/build]
    priority: 50
    job:
      class: RunADTests
      args:
        build_url: '{fedora-latest/build_url}'
        test_suite: test_integration/test_trust.py::TestTrust
        template: *ci-master-latest
        timeout: 7200
        topology: *adroot_adchild_adtree_master_1client

  fedora-latest/test_trust_39:
    requires: [fedora-latest/build]
    priority: 50
    job:
      class: RunADTests
      args:
        build_url: '{fedora-latest/build_url}'
        test_suite: test_integration/test_trust.py::TestTrust
        template: *ci-master-latest
        timeout: 7200
        topology: *adroot_adchild_adtree_master_1client

  fedora-latest/test_trust_40:
    requires: [fedora-latest/build]
    priority: 50
    job:
      class: RunADTests
      args:
        build_url: '{fedora-latest/build_url}'
        test_suite: test_integration/test_trust.py::TestTrust
        template: *ci-master-latest
        timeout: 7200
        topology: *adroot_adchild_adtree_master_1client
